server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pragma_stock_fullstack
    username: root
    password: b3192621119B
    jpa:
      hibernate:
        ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"